services:
  liveness:
    image: liveness:v1.0.0
    container_name: liveness
    ports:
      - "5173:80"
    depends_on:
      - api-liveness

  api-liveness:
    image: api-liveness:v1.0.0
    container_name: api-liveness
    ports:
      - "3301:80"
    environment:
      APPLICATION_SERVICE: api-liveness
      APPLICATION_ENVIRONMENT: development
      APPLICATION_CLIENT: "http://localhost:5173"
      HTTP_PORT: ":80"
      SERVICE_SELF_MANAGED_SERVICE_PREDICTION_ENDPOINT: "self-managed-prediction-service-liveness:50051"
      SERVICE_MANAGED_SERVICE_PREDICTION_ENDPOINT: "http://managed-prediction-service-liveness:80/predict"
      SERVICE_MANAGED_SERVICE_PREDICTION_AUTHORIZATION_TOKEN: "super-secret-token"
    depends_on:
      - self-managed-prediction-service-liveness
      - managed-prediction-service-liveness

  self-managed-prediction-service-liveness:
    image: prediction-liveness:v1.0.0
    container_name: self-managed-prediction-service-liveness
    command: ["grpc"]
    environment:
      APPLICATION_SERVICE: self-managed-prediction-service-liveness
      APPLICATION_ENVIRONMENT: development
      GRPC_PORT: ":50051"
      HTTP_PORT: "80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  managed-prediction-service-liveness:
    image: prediction-liveness:v1.0.0
    container_name: managed-prediction-service-liveness
    command: ["http"]
    environment:
      APPLICATION_SERVICE: managed-prediction-service-liveness
      APPLICATION_ENVIRONMENT: development
      GRPC_PORT: ":50051"
      HTTP_PORT: "80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  loki:
    image: grafana/loki:3.7.8
    container_name: loki-liveness
    command:
      - "-config.file=/etc/loki/loki-config.yaml"
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/loki-config.yaml:ro
      - loki-data:/tmp/loki

  alloy:
    image: grafana/alloy:v1.20.0
    container_name: alloy-liveness
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    ports:
      - "127.0.0.1:12345:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy-data:/var/lib/alloy/data
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:13.2.2
    container_name: grafana-liveness
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

volumes:
  loki-data:
  alloy-data:
  grafana-data:
